// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/gosher.proto

package schemas

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GosherClient is the client API for Gosher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GosherClient interface {
	SayHi(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	ReceiveHi(ctx context.Context, in *Identity, opts ...grpc.CallOption) (Gosher_ReceiveHiClient, error)
}

type gosherClient struct {
	cc grpc.ClientConnInterface
}

func NewGosherClient(cc grpc.ClientConnInterface) GosherClient {
	return &gosherClient{cc}
}

func (c *gosherClient) SayHi(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/schemas.Gosher/SayHi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gosherClient) ReceiveHi(ctx context.Context, in *Identity, opts ...grpc.CallOption) (Gosher_ReceiveHiClient, error) {
	stream, err := c.cc.NewStream(ctx, &Gosher_ServiceDesc.Streams[0], "/schemas.Gosher/ReceiveHi", opts...)
	if err != nil {
		return nil, err
	}
	x := &gosherReceiveHiClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Gosher_ReceiveHiClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type gosherReceiveHiClient struct {
	grpc.ClientStream
}

func (x *gosherReceiveHiClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GosherServer is the server API for Gosher service.
// All implementations must embed UnimplementedGosherServer
// for forward compatibility
type GosherServer interface {
	SayHi(context.Context, *Request) (*Response, error)
	ReceiveHi(*Identity, Gosher_ReceiveHiServer) error
	mustEmbedUnimplementedGosherServer()
}

// UnimplementedGosherServer must be embedded to have forward compatible implementations.
type UnimplementedGosherServer struct {
}

func (UnimplementedGosherServer) SayHi(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHi not implemented")
}
func (UnimplementedGosherServer) ReceiveHi(*Identity, Gosher_ReceiveHiServer) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveHi not implemented")
}
func (UnimplementedGosherServer) mustEmbedUnimplementedGosherServer() {}

// UnsafeGosherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GosherServer will
// result in compilation errors.
type UnsafeGosherServer interface {
	mustEmbedUnimplementedGosherServer()
}

func RegisterGosherServer(s grpc.ServiceRegistrar, srv GosherServer) {
	s.RegisterService(&Gosher_ServiceDesc, srv)
}

func _Gosher_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GosherServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schemas.Gosher/SayHi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GosherServer).SayHi(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gosher_ReceiveHi_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Identity)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GosherServer).ReceiveHi(m, &gosherReceiveHiServer{stream})
}

type Gosher_ReceiveHiServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type gosherReceiveHiServer struct {
	grpc.ServerStream
}

func (x *gosherReceiveHiServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

// Gosher_ServiceDesc is the grpc.ServiceDesc for Gosher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gosher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schemas.Gosher",
	HandlerType: (*GosherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHi",
			Handler:    _Gosher_SayHi_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveHi",
			Handler:       _Gosher_ReceiveHi_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/gosher.proto",
}
